[package]
name = "rs-get"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
console = "0.15.8"
indicatif = "0.17.8"
reqwest = {  version = "0.12.7", features = ["blocking"] }
